name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io  # ghcr 주소 
          image: ghcr.io/k021/mrxob
          # <GITHUB_USERNAME>/<GITHUB_REPO>/<DOCKER_IMAGE_NAME>
          repository: k021/mrx-onboarding/mrxob
          tag_with_ref: true
